Controllers/HomeController.cs
using System.Diagnostics;
using ActualTeast.Models;
using ActualTeast.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ActualTeast.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDBContext _context;

        public HomeController(ApplicationDBContext context,ILogger<HomeController> logger)
        {
            _context = context;
            _logger=logger;
        }

        public async Task< IActionResult > Index(string sortOrder,
    string currentFilter,
    string searchString,
    int? pageNumber)
        {
            ViewData["CurrentSort"]=sortOrder;
            ViewData["NameSortParm"]=String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["DateSortParm"]=sortOrder=="date" ? "date_desc" : "date";
            if(searchString!=null)
            {
                pageNumber=1;
            }
            else
            {
                searchString=currentFilter;
            }

            ViewData["CurrentFilter"]=searchString;

            var users = from s in _context.Plogs.Include(p => p.Ratings)
                .Include(p => p.Owner)
                .Include(p => p.Comments)
                .ThenInclude(c => c.Commenter)
                        select s;
            if(!String.IsNullOrEmpty(searchString))
            {
                    users=users.Where(s => s.Title.Contains(searchString)||s.Content.Contains(searchString));
            }
            switch(sortOrder)
            {
                case "title_desc":
                users=users.OrderByDescending(s => s.Title);
                break;
                case "date":
                users=users.OrderBy(s => s.PublishDate);
                break;
                case "date_desc":
                users=users.OrderByDescending(s => s.PublishDate);
                break;
                default:
                users=users.OrderBy(s => s.Title);
                break;
            }

            int pageSize = 1;
            return View(await PaginatedList<Plog>.CreateAsync(source: users.AsNoTracking(),pageNumber??1,pageSize));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0,Location = ResponseCacheLocation.None,NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId=Activity.Current?.Id??HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ActualTeast.Models;
using Microsoft.AspNetCore.Identity;
using ActualTeast.ViewModels;

namespace ActualTeast.Controllers
{
    public class PlogsController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly UserManager<User> _userManager;

        public PlogsController(ApplicationDBContext context,UserManager<User> userManager)
        {
            _userManager=userManager;
            _context=context;
        }

        // GET: Plogs
        public async Task<IActionResult> Index()
        {
            var applicationDBContext = _context.Plogs.Include(p => p.Owner);
            return View(await applicationDBContext.ToListAsync());
        }

        // GET: Plogs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if(id==null||_context.Plogs==null)
            {
                return NotFound();
            }

            var plog = await _context.Plogs
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id==id);
            if(plog==null)
            {
                return NotFound();
            }

            return View(plog);
        }

        // GET: Plogs/Create
        public IActionResult Create()
        {
            ViewData["Owner"]=User.Identity.Name;
            return View();
        }

        // POST: Plogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddPlogViewModel newPlog)
        {
            if(ModelState.IsValid)
            {
                Plog plog = new() {
                    PublishDate=DateTime.Now,
                    OwnerId=_userManager.GetUserId(User),
                    Content=newPlog.Content,
                    Title=newPlog.Title,

                };
                _context.Add(plog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"Home");
            }
            ViewData["Owner"]=User.Identity.Name;
            return View(newPlog);
        }

        // GET: Plogs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if(id==null||_context.Plogs==null)
            {
                return NotFound();
            }

            var plog = await _context.Plogs.FindAsync(id);
            if(plog==null)
            {
                return NotFound();
            }
            ViewData["Owner"]=User.Identity.Name;
            AddPlogViewModel addPlogViewModel = new() {
                Content=plog.Content,
                Title=plog.Title,
                Id=plog.Id
            };
            return View(addPlogViewModel);
        }

        // POST: Plogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,AddPlogViewModel newPlog)
        {
            if(id!=newPlog.Id)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                try
                {
                    Plog plog = new() {
                        Id=newPlog.Id,
                        Title=newPlog.Title,
                        PublishDate=DateTime.Now,
                        Content=newPlog.Content,
                        OwnerId=_userManager.GetUserId(User)
                    };
                    _context.Update(plog);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if(!PlogExists(newPlog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index),"Home");
            }
            ViewData["Owner"]=User.Identity.Name;
            return View(newPlog);
        }

        // GET: Plogs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if(id==null||_context.Plogs==null)
            {
                return NotFound();
            }

            var plog = await _context.Plogs
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id==id);
            if(plog==null)
            {
                return NotFound();
            }

            return View(plog);
        }

        // POST: Plogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if(_context.Plogs==null)
            {
                return Problem("Entity set 'ApplicationDBContext.Plogs'  is null.");
            }
            var plogComments =await _context.Comments.Where(c=>c.PlogId==id).ToListAsync();
            if(plogComments.Any())
                _context.RemoveRange(plogComments);
            var plogRatings = await _context.Ratings.Where(r=>r.PlogId==id).ToListAsync();
            if (plogRatings.Any())
            _context.RemoveRange(plogRatings);
            var plog = await _context.Plogs.FindAsync(id);
            if(plog!=null)
            {
                _context.Plogs.Remove(plog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index),"Home");
        }

        private bool PlogExists(string id)
        {
            return (_context.Plogs?.Any(e => e.Id==id)).GetValueOrDefault();
        }
    }
}

Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ActualTeast.Models;
using ActualTeast.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace ActualTeast.Controllers
{
    public class RatingsController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly UserManager<User> _userManager;

        public RatingsController(ApplicationDBContext context,UserManager<User> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Ratings
        public async Task<IActionResult> Index()
        {
            var applicationDBContext = _context.Ratings.Include(p => p.Plog).Include(p => p.User);
            return View(await applicationDBContext.ToListAsync());
        }

        // GET: Ratings/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Ratings == null)
            {
                return NotFound();
            }

            var plogRatings = await _context.Ratings
                .Include(p => p.Plog)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (plogRatings == null)
            {
                return NotFound();
            }

            return View(plogRatings);
        }

        // GET: Ratings/Create
        public async Task<IActionResult> Create(string id)
        {
            if(id==null||_context.Ratings==null)
            {
                return NotFound();
            }
            var plog = await _context.Plogs.Where(p => p.Id==id)
                .Include(p => p.Owner)
                .Include(p => p.Ratings)
                .FirstOrDefaultAsync();
            if(plog==null)
                return NotFound();
            ViewData["Plog"] =plog;
            ViewData["User"] =User.Identity.Name;
            return View();
        }

        // POST: Ratings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string id,RateingPlogViewModel newPlogRatings)
        {
            if(id != newPlogRatings.PlogId)
            {
                return NotFound();
            }
            PlogRatings plogRatings = new() {
                PlogId = id,
                Rating = newPlogRatings.Rating,
                UserId = _userManager.GetUserId(User)
            } ;
            if (ModelState.IsValid)
            {
                var rate = await _context.Ratings.Where(r => r.UserId==plogRatings.UserId&&plogRatings.PlogId==r.PlogId).FirstOrDefaultAsync();
                if(rate==null)
                {

                _context.Add(plogRatings);
                }
                else
                {
                    rate.Rating=plogRatings.Rating;
                    _context.Update(rate);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"Home");
            }
            var plog = await _context.Plogs.Where(p => p.Id==id)
                .Include(p => p.Owner)
                .Include(p => p.Ratings)
                .FirstOrDefaultAsync();
            if(plog==null)
                return NotFound();
            ViewData["Plog"]=plog;
            ViewData["User"]=User.Identity.Name;
            return View(plogRatings);
        }

        // GET: Ratings/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Ratings == null)
            {
                return NotFound();
            }

            var plogRatings = await _context.Ratings.FindAsync(id);
            if (plogRatings == null)
            {
                return NotFound();
            }
            ViewData["PlogId"] = new SelectList(_context.Plogs, "Id", "Id", plogRatings.PlogId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", plogRatings.UserId);
            return View(plogRatings);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserId,PlogId,Rating")] PlogRatings plogRatings)
        {
            if (id != plogRatings.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plogRatings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlogRatingsExists(plogRatings.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index),"Home");
            }
            ViewData["PlogId"] = new SelectList(_context.Plogs, "Id", "Id", plogRatings.PlogId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", plogRatings.UserId);
            return View(plogRatings);
        }

        // GET: Ratings/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Ratings == null)
            {
                return NotFound();
            }

            var plogRatings = await _context.Ratings
                .Include(p => p.Plog)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (plogRatings == null)
            {
                return NotFound();
            }

            return View(plogRatings);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Ratings == null)
            {
                return Problem("Entity set 'ApplicationDBContext.Ratings'  is null.");
            }
            var plogRatings = await _context.Ratings.FindAsync(id);
            if (plogRatings != null)
            {
                _context.Ratings.Remove(plogRatings);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlogRatingsExists(string id)
        {
          return (_context.Ratings?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using ActualTeast.Models
@using System.Security.Claims;
@using ActualTeast.Constants;
@using ActualTeast.Utils;

@model PaginatedList<Plog>

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@{
    ViewData["Title"]="Home Page";
    var curre = User.FindFirstValue(ClaimTypes.Role);
    var userId = UserManager.GetUserId(User);
    var roleData = new ViewDataDictionary(ViewData) {
        {"role",curre}
    };
}

<div class="text-center">
    <div class="d-flex justify-content-around align-items-center mb-3">
        <div class="me-auto">

            <a asp-controller="Plogs" asp-action="Create" class="card-link">Add Plog</a>
        </div>
        <label class="col-form-label me-2" for="SearchOption">Sort by</label>
        <div class="justify-content-end me-2">
            <form class="input-group" asp-action="Index">
                <select name="sortOrder" class="form-select">
                    <option value="">Title</option>
                    <option value="title_desc">Title Desc</option>
                    <option value="date">Date</option>
                    <option value="date_desc">Date Desc</option>
                </select>
                <button type="submit"
                        class="btn btn-outline-primary">
                    Sort
                </button>
            </form>
        </div>
        <label class="col-form-label me-2" for="SearchOption">Search in</label>
        <div class="justify-content-end">
            <form class="input-group" asp-action="Index">
                <input type="search" class="form-control" name="searchString" placeholder="Search for plog" aria-label="Search" />
                <button type="submit"
                        class="btn btn-outline-primary">
                    Search
                </button>
            </form>
        </div>
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            <i class="bx bx-skip-previous"></i> Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next <i class="bx bx-skip-next"></i>
        </a>
    </div>
    @foreach(var plog in Model.Items )
    {
        <div class="container ">
            <partial name="_PlogCard" model=@plog />
            <div class="d-flex flex-row justify-content-between">
                <p class="fs-3"> @plog.Comments.Count Comment(s) </p>
                @if(@SignInManager.IsSignedIn(User))
                {

                    <div>
                        <a asp-controller="Comments" asp-action="Create" asp-route-id="@plog.Id" class="card-link">Add Comment</a>
                        <a asp-controller="Ratings" asp-action="Create" asp-route-id="@plog.Id" class="card-link">Rate</a>
                    </div>
                }
            </div>
            @foreach(var comment in plog.Comments)
            {
                <div class="card text-start mb-3">
                    <div class="card-body">
                        <h5 class="card-title">@comment.Commenter.FirstName @comment.Commenter.LastName </h5>
                        <p class="card-text">@comment.Text </p>
                        @if(@SignInManager.IsSignedIn(User)&&userId==comment.CommenterId)
                        {
                            <a asp-controller="Comments" asp-action="Edit" asp-route-id="@comment.Id" class="card-link">Edit</a>
                            <a asp-controller="Comments" asp-action="Delete" asp-route-id="@comment.Id" class="card-link">Delete</a>
                        }
                    </div>
                </div>
            }
        </div>
    }
</div>